#!/bin/bash

gh issue create --title "FF-1.1 Define DynamoDB schema" --body "Design the single-table schema for feature flags and targeting rules." --label "type:infrastructure" --label "env:aws" --label "mvp"
gh issue create --title "FF-1.2 Create IaC template" --body "Use Serverless Framework or SAM to define infrastructure." --label "type:infrastructure" --label "env:aws" --label "mvp"
gh issue create --title "FF-1.3 Deploy to dev environment" --body "Deploy DynamoDB table and IAM roles in dev." --label "type:infrastructure" --label "env:aws" --label "mvp"
gh issue create --title "FF-1.4 Add sample seed data" --body "Seed table with one sample flag across environments." --label "type:infrastructure" --label "env:aws" --label "mvp"
gh issue create --title "FF-2.1 Define GraphQL schema" --body "Define types for Flag, Environment, and TargetRule." --label "type:api" --label "mvp"
gh issue create --title "FF-2.2 Implement mutations" --body "Implement createFlag, updateFlag, deleteFlag." --label "type:api" --label "mvp"
gh issue create --title "FF-2.3 Implement queries" --body "Implement listFlags, getFlag, evaluateFlag." --label "type:api" --label "mvp"
gh issue create --title "FF-2.4 Add input validation" --body "Validate GraphQL inputs and return helpful errors." --label "type:api" --label "mvp"
gh issue create --title "FF-2.5 Add unit tests for resolvers" --body "Write tests for all GraphQL resolvers." --label "type:api" --label "mvp"
gh issue create --title "FF-2.6 Document GraphQL API" --body "Write documentation and usage examples for the GraphQL API." --label "type:documentation" --label "mvp"
gh issue create --title "FF-3.1 Implement IFeatureDefinitionProvider" --body "Implement a provider that pulls feature flags from DynamoDB." --label "type:package" --label "env:dotnet" --label "mvp"
gh issue create --title "FF-3.2 Support targeting logic" --body "Extend provider to support user/org/environment targeting." --label "type:package" --label "env:dotnet" --label "mvp"
gh issue create --title "FF-3.3 Write sample ASP.NET Core usage" --body "Show how to use Windwalker Flags in a .NET 8+ app." --label "type:documentation" --label "env:dotnet" --label "mvp"
gh issue create --title "FF-3.4 Publish as reusable package" --body "Package and publish to NuGet as Windwalker.FeatureFlags." --label "type:package" --label "env:dotnet" --label "mvp"
gh issue create --title "FF-4.1 Define minimal API" --body "Design IsEnabled(flag, context) method for .NET Framework." --label "type:package" --label "env:dotnet" --label "mvp"
gh issue create --title "FF-4.2 Implement evaluation client" --body "Call the GraphQL evaluation endpoint from .NET Framework." --label "type:package" --label "env:dotnet" --label "mvp"
gh issue create --title "FF-4.3 Add local caching" --body "Cache feature flag results in-memory with TTL." --label "type:package" --label "env:dotnet" --label "mvp"
gh issue create --title "FF-4.4 Publish to NuGet" --body "Publish as Windwalker.FeatureFlags.NetFx." --label "type:package" --label "env:dotnet" --label "mvp"
gh issue create --title "FF-5.1 Setup Next.js project" --body "Create UI project and apply styling framework." --label "type:ui" --label "env:react" --label "mvp"
gh issue create --title "FF-5.2 Add Cognito login" --body "Secure the UI using AWS Cognito." --label "type:ui" --label "env:react" --label "env:aws" --label "mvp"
gh issue create --title "FF-5.3 Build Flag List screen" --body "List flags per environment, sortable and filterable." --label "type:ui" --label "env:react" --label "mvp"
gh issue create --title "FF-5.4 Add create/edit form" --body "Create form to add and edit feature flags." --label "type:ui" --label "env:react" --label "mvp"
gh issue create --title "FF-5.5 Add delete confirmation" --body "Allow safe deletion of feature flags." --label "type:ui" --label "env:react" --label "mvp"
gh issue create --title "FF-5.6 Connect to GraphQL" --body "Wire up the UI to the backend GraphQL API." --label "type:ui" --label "env:react" --label "mvp"
gh issue create --title "FF-6.1 Create Cognito pool" --body "Create user pool and client for authentication." --label "type:infrastructure" --label "env:aws" --label "mvp"
gh issue create --title "FF-6.2 Define Cognito groups" --body "Setup groups like dev-admin, prod-admin." --label "type:infrastructure" --label "env:aws" --label "mvp"
gh issue create --title "FF-6.3 Protect GraphQL mutations" --body "Restrict changes based on Cognito group." --label "type:api" --label "env:aws" --label "mvp"
gh issue create --title "FF-6.4 Enforce env access in UI" --body "UI should reflect access control rules per environment." --label "type:ui" --label "env:react" --label "env:aws" --label "mvp"
gh issue create --title "FF-8.1 Define JSON schema for targeting rules" --body "Design a JSON-based rule schema for user/org/condition logic." --label "type:api" --label "mvp"
gh issue create --title "FF-8.2 Extend evaluation API to support rules" --body "Update evaluateFlag to apply targeting logic." --label "type:api" --label "mvp"
gh issue create --title "FF-8.3 Implement rule parsing and logic" --body "Parse rule JSON and evaluate context at runtime." --label "type:api" --label "mvp"
gh issue create --title "FF-8.4 Add tests for rule edge cases" --body "Cover user/org match, OR logic, fallbacks." --label "type:api" --label "mvp"
gh issue create --title "FF-9.1 Add targeting editor to UI" --body "Build UI for creating/editing targeting rules." --label "type:ui" --label "env:react" --label "mvp"
gh issue create --title "FF-9.2 Support rule types" --body "Allow targeting by user, org, or advanced JSON." --label "type:ui" --label "env:react" --label "mvp"
gh issue create --title "FF-9.3 Add JSON preview and validation" --body "Show rule JSON with validation and editing." --label "type:ui" --label "env:react" --label "mvp"
gh issue create --title "FF-10.1 Define audit log entry format" --body "Decide how to structure flag change history entries." --label "type:api" --label "mvp"
gh issue create --title "FF-10.2 Store logs in DynamoDB" --body "Write change history to a new table or SK." --label "type:api" --label "env:aws" --label "mvp"
gh issue create --title "FF-10.3 Log all mutations" --body "Track who changed what, when, and the previous value." --label "type:api" --label "mvp"
gh issue create --title "FF-11.1 Add History tab to UI" --body "Show list of changes to each flag." --label "type:ui" --label "env:react" --label "mvp"
gh issue create --title "FF-11.2 Display change records" --body "Format and show change log data clearly." --label "type:ui" --label "env:react" --label "mvp"
gh issue create --title "FF-12.1 Enforce prod-only admins" --body "Deny prod edits to non-prod Cognito groups." --label "type:api" --label "env:aws" --label "mvp"
gh issue create --title "FF-12.2 Disable UI edits for unauthorized users" --body "Gray out or hide buttons based on group." --label "type:ui" --label "env:react" --label "mvp"
gh issue create --title "FF-12.3 Add error feedback for denied access" --body "Show user-friendly messages when access is blocked." --label "type:ui" --label "env:react" --label "mvp"
gh issue create --title "FF-13.1 Add evaluateFlags query" --body "Support checking multiple flags at once." --label "type:api" --label "future"
gh issue create --title "FF-13.2 Support context in batch" --body "Pass context for all evaluations in one call." --label "type:api" --label "future"
gh issue create --title "FF-13.3 Document performance" --body "Guide devs on batching best practices." --label "type:documentation" --label "future"
gh issue create --title "FF-14.1 Log evaluation events" --body "Track each flag evaluation for metrics." --label "type:api" --label "env:aws" --label "nice-to-have"
gh issue create --title "FF-14.2 Store usage counters" --body "Count how often each flag is checked." --label "type:api" --label "nice-to-have"
gh issue create --title "FF-14.3 Visualize usage in UI" --body "Optional chart or heatmap for flag usage." --label "type:ui" --label "env:react" --label "nice-to-have"
gh issue create --title "FF-15.1 Add rolloutPercentage to flags" --body "Include a percentage in flag metadata." --label "type:api" --label "future"
gh issue create --title "FF-15.2 Hash user ID for rollout logic" --body "Implement deterministic rollout logic." --label "type:api" --label "future"
gh issue create --title "FF-15.3 Document rollout usage" --body "Explain how to use rollout safely in prod." --label "type:documentation" --label "future"
gh issue create --title "FF-16.1 Add Windwalker branding" --body "Apply consistent brand/logo/fonts." --label "type:ui" --label "env:react" --label "nice-to-have"
gh issue create --title "FF-16.2 Support dark/light mode" --body "Allow user toggle or system preference." --label "type:ui" --label "env:react" --label "nice-to-have"
gh issue create --title "FF-16.3 Improve UX feedback" --body "Better error/success messages, toasts." --label "type:ui" --label "env:react" --label "nice-to-have"
gh issue create --title "FF-17.1 Create deploy script" --body "Script deploys for full stack to AWS." --label "type:infrastructure" --label "env:aws" --label "future"
gh issue create --title "FF-17.2 Support environment toggle" --body "Switch between dev and prod deploys." --label "type:infrastructure" --label "env:aws" --label "future"
gh issue create --title "FF-17.3 Write setup docs for clients" --body "Step-by-step for installing Windwalker Flags." --label "type:documentation" --label "future"
gh issue create --title "FF-18.1 Create demo flag set" --body "Sample flags for dev/testing/demo use." --label "type:infrastructure" --label "env:aws" --label "future"
gh issue create --title "FF-18.2 Add JSON seeder" --body "Script to seed flags from JSON file." --label "type:infrastructure" --label "future"
gh issue create --title "FF-18.3 Optional public demo login" --body "Setup optional demo user in Cognito." --label "type:infrastructure" --label "env:aws" --label "nice-to-have"
gh issue create --title "FF-19.1 Add repo badges" --body "Add shields for license, build, etc." --label "type:documentation" --label "future"
gh issue create --title "FF-19.2 Create roadmap section" --body "List key milestones in README." --label "type:documentation" --label "future"
gh issue create --title "FF-19.3 Add contributing guide" --body "Setup basic contributor docs." --label "type:documentation" --label "future"
gh issue create --title "FF-19.4 Add LICENSE file" --body "Use MIT license for Windwalker Flags." --label "type:documentation" --label "future"
