AWSTemplateFormatVersion: '2010-09-09'
Description: |
  DynamoDB table definition for the Windwalker Flags service.
  This table uses a single‑table design to store feature flags, per‑environment
  settings, targeting rules and change logs.  It defines a partition key (PK)
  and sort key (SK) and a Global Secondary Index (GSI1) for querying flags by
  environment.  The table is configured for on‑demand billing, server‑side
  encryption, point‑in‑time recovery and streams to support future change
  notifications.

Parameters:
  TableName:
    Type: String
    Description: Name of the DynamoDB table to create
    Default: windwalker-flags

Resources:
  FeatureFlagsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref TableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
        - AttributeName: GSI1PK
          AttributeType: S
        - AttributeName: GSI1SK
          AttributeType: S
      KeySchema:
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: GSI1PK
              KeyType: HASH
            - AttributeName: GSI1SK
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true
      StreamSpecification:
        StreamViewType: NEW_AND_OLD_IMAGES

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref FeatureFlagsTable
  TableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt FeatureFlagsTable.Arn
